[package]
name = "flight_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow="^11.1.0"
arrow-flight="^11.1.0"
tonic="^0.7.1"
tokio="^1.17.0"

